### ISSUE TITLE
Features Todo

### ISSUE THREAD

**Issue by BradDenver** [BradDenver/react-static-site#1]
- [ ] rss feed
- [ ] site tree
- [ ] default contentForPost to look for "path + .md” if md not set in paths.js
- [ ] make blog path configureable e.g. /blog/x or /posts/x
- [ ] draft flag for posts to filter out when compiling for prod (add red header when dev)
- [ ] clean public folder before build
- [ ] 404 page
- [ ] source maps
- [ ] paginated post archive
- [ ] blog categories
